# Generated by Django 3.2.6 on 2021-08-18 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='size',
            name='eu_size',
            field=models.IntegerField(unique=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='uk_size',
            field=models.FloatField(unique=True),
        ),
    ]
