# Generated by Django 3.2.6 on 2021-08-18 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('size', '0002_auto_20210818_1238'),
        ('shoes', '0002_auto_20210818_1238'),
        ('variant', '0002_variant_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='shoe',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='shoes.shoe'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant', to='size.size'),
        ),
    ]
