# Generated by Django 3.2.6 on 2021-08-17 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(choices=[('Nike', 'Nike'), ('Adidas', 'Adidas'), ('Reebok', 'Reebok'), ('Vans', 'Vans'), ('Superga', 'Superga'), ('DC', 'DC')], default='Nike', max_length=50)),
                ('model_name', models.CharField(max_length=200)),
            ],
        ),
    ]
