# Generated by Django 3.2.6 on 2021-08-18 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shoes', '0002_auto_20210818_1238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoe',
            name='picture',
            field=models.ImageField(default=None, upload_to='images/'),
        ),
    ]
